version: "3"
services:
  client:
    build: client/
    restart: always
    ports:
      - 3000:3000
  server:
    build: server/
    restart: always
    ports: 
    - 8080:8080
  proxy:
    image: nginx:mainline
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80